<?php


namespace Unidade\Mensageria;


use Mensageria\Eventos\Publicavel;
use Mensageria\Fachadas\Mensageria;
use Testes\TestCase;
use Testes\Mock\Adaptadores\RabbitMQAdaptador;
use PhpAmqpLib\Message\AMQPMessage;

class MensageriaTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Mensageria::registrar(function() {
            $mockAdapter = new RabbitMQAdaptador();
            return new \Mensageria\Mensageria(null, $mockAdapter, $mockAdapter);
        });
    }

    public function testConsumir() {
        $this->registrarMensagem('mensageria.consumir');

        $entrou = false;
        Mensageria::consumir(function(AMQPMessage $mensagem) use (&$entrou) {
            $entrou = true;
        });
        $this->assertTrue($entrou, "Não entrou no callback");
    }

    public function testPublicar() {
        Mensageria::publicar(new Publicavel(array("mensagem de teste!")));
    }
}
